import { boot, type ColyseusTestServer } from "@colyseus/testing";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { server } from "../../src/server/app.config.ts";
import { closeGameDatabase, gameDatabase } from "../../src/server/db/GameDatabase.ts";
import type { TdmRoom } from "../../src/server/rooms/TdmRoom.ts";
import { MAX_HP, SCORE_LIMIT } from "../../src/shared/constants.ts";
import { MatchStatsMessage, RewardMessage } from "../../src/net/messages.ts";
import { DAILY_POOL, WEEKLY_POOL, progressFrom } from "../../src/shared/challenges.ts";
import { LEVEL_TRACK } from "../../src/shared/cosmetics.ts";
import { levelProgress } from "../../src/shared/progression.ts";

describe("room match statistics", () => {
  let colyseus: ColyseusTestServer<typeof server>;
  beforeAll(async () => { colyseus = await boot(server); });
  afterAll(async () => { await colyseus.shutdown(); await closeGameDatabase(); });
  it("sends human and guest stats, resets a death streak and stores precision and weapon XP", async () => {
    const db = await gameDatabase();
    const { token, profile } = await db.createGuest("Archer");
    const challenges = await db.challenges(profile.id);
    const client = await colyseus.sdk.joinOrCreate("tdm", { name: "Archer", token, test: true });
    const guest = await colyseus.sdk.joinOrCreate("tdm", { name: "Guest", test: true });
    await client.waitForInitialState(); await guest.waitForInitialState();
    const room = colyseus.getRoomById<TdmRoom>(client.roomId);
    const statsMessage = new Promise<unknown>((resolve) => client.onMessage("matchStats", resolve));
    const guestMessage = new Promise<unknown>((resolve) => guest.onMessage("matchStats", resolve));
    const rewardMessage = new Promise<unknown>((resolve) => client.onMessage("rewards", resolve));
    const me = room.state.players.get(client.sessionId)!;
    const other = room.state.players.get(guest.sessionId)!;
    other.team = me.team === 0 ? 1 : 0; me.spawnProtectMs = 0; other.spawnProtectMs = 0;
    room.state.phase = "live"; room.state.phaseEndsAtMs = Number.MAX_SAFE_INTEGER;
    const damage = room as unknown as { dealDamage(a: string, t: string, d: number, w: "arrow" | "dagger" | "boulder", h: boolean, x: number, z: number, origin?: { x: number; z: number }): void; resetPlayers(): void };
    other.x = 45; other.z = 0; me.x = 44; me.z = 0;
    damage.dealDamage(client.sessionId, guest.sessionId, MAX_HP, "arrow", true, 0, 0, { x: 0, z: 0 });
    other.alive = true; other.hp = MAX_HP;
    damage.dealDamage(client.sessionId, guest.sessionId, MAX_HP, "dagger", false, 0, 0);
    other.alive = true; other.hp = MAX_HP;
    damage.dealDamage(guest.sessionId, client.sessionId, MAX_HP, "arrow", false, 0, 0);
    me.alive = true; me.hp = MAX_HP;
    if (me.team === 0) room.state.scoreSun = SCORE_LIMIT - 1; else room.state.scoreMoon = SCORE_LIMIT - 1;
    damage.dealDamage(client.sessionId, guest.sessionId, MAX_HP, "boulder", false, 0, 0);
    const message = MatchStatsMessage.parse(await statsMessage);
    expect(message.stats).toEqual({ kills: 3, deaths: 1, assists: 0, headshots: 1, longShots: 1, longestShotM: 45, daggerKills: 1, boulderKills: 1, zipKills: 0, robinHoods: 0, ropeCuts: 0, swats: 0, scatterKills: 0, tetherRides: 0, streak: 1, bestStreak: 2, won: true });
    expect(message.medals).toEqual(["eagleEye", "upClose", "trapper"]);
    expect(MatchStatsMessage.parse(await guestMessage).stats).toMatchObject({ kills: 1, deaths: 3, streak: 0, bestStreak: 1, won: false });
    const completed = [...challenges.daily, ...challenges.weekly].filter((entry) => progressFrom(message.stats, [...DAILY_POOL, ...WEEKLY_POOL].find((definition) => definition.id === entry.id)!) >= entry.target);
    const xp = 575 + 100 + completed.reduce((sum, entry) => sum + entry.reward.xp, 0);
    const ink = 23 + 25 + completed.reduce((sum, entry) => sum + entry.reward.ink, 0) + LEVEL_TRACK.filter((entry) => entry.level <= levelProgress(xp).level).reduce((sum, entry) => sum + entry.ink, 0);
    expect(RewardMessage.parse(await rewardMessage)).toMatchObject({ xp, ink, streakDays: 1 });
    await room.rewardsSettled;
    expect(await db.profile(profile.id)).toMatchObject({ xp, ink });
    damage.resetPlayers();
    const map = (room as unknown as { humanStats: Map<string, { kills: number; headshots: number; bestStreak: number }> }).humanStats;
    expect(map.get(client.sessionId)).toMatchObject({ kills: 0, headshots: 0, bestStreak: 0 });
    await client.leave(); await guest.leave();
  });
});
